-- Booking System V2 — Field Naming Convention
--
-- The booking page (Step 3) collects data using these UI field names:
--
--   UI field name       → database column
--   ─────────────────────────────────────
--   contactName         → parent_name
--   contactEmail        → email
--   contactPhone        → phone
--   athleteName         → player_name
--   athleteAge          → age_group
--   experienceLevel     → experience
--   notes               → notes
--
-- The API route (/api/bookings POST) accepts both new and legacy field names
-- and maps them to the existing schema (migrations 001 + 002).
-- No schema changes are required for V2.
--
-- This is a documentation-only migration — no SQL to execute.
